name: jtt_commandline
description: A tablet weaving command-line application.
version: 0.0.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  prompter_jtt: ^0.0.3
  xml: ^6.1.0
  hex: ^0.2.0
  json_annotation: ^4.5.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0