name: jtt_commandline
description: A tablet weaving command-line application.
version: 0.0.1

environment:
  sdk: ^2.2.0

dependencies:
  prompter_jtt: ^0.0.2
  xml: ^4.3.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
